### ISSUE TITLE
datetime & tzinfo

### ISSUE THREAD

**Issue by tikismoke** [quentin7b/xee-sdk-python#11]
Pour chaque requête, j’obtiens ce genre de résultats:

`Location(latitude=4xx.440586, longitude=xx.08945, altitude=xx5.2, satellites=10, heading=2xx.85, date=datetime.datetime(2016, 9, 10, 11, 25, 7, 236000, tzinfo=<isodate.tzinfo.Utc object at 0x7fc264cb0810>))`

Comme si les valeurs n'étaient pas converties ou une partie du code pas executé.

**Comment by qk7b** [comment]
How !

Weird, maybe some float / double lost of precision !

I'll have a look quickly

**Comment by tikismoke** [comment]
If I replace by simple location['date'] in entitys for example I got the date complete correctly. Like 2013-09-13......

Do not really understand why isodate do not works.

**Comment by qk7b** [comment]
Hum, is the issue about `latitude` and `longitude` or in the `date` ?

**Comment by tikismoke** [comment]
It's date issue on all requests position status trips etc...., I change the lat/lon voluntary in the copy/paste sorry :)

**Comment by qk7b** [comment]
No problem (I've read the issue title again, seems legit ;))! 

I think the format of the date is correct , isn't it ? 
Maybe just the representation of `isodate` ? or is the content wrong ?

**Comment by tikismoke** [comment]
In my Apps case, for each requests i will store the timestamp or date of the location for example by explosing the tupple.
But for date it will looks like  "datetime.datetime(2016, 9, 10, 11, 25, 7, 236000, tzinfo=<isodate.tzinfo.Utc object at 0x7fc264cb0810>)" wich is really not usefull as is.

A simple timestamp or the date store as is without passing it to datetime or isodate seems better.

It's only a point of view, but for the moment it's really not usefull at all.

**Comment by qk7b** [comment]
So why not converting this into timestamp within your code ? 
Like doing something like http://stackoverflow.com/questions/12165691/python-datetime-with-timezone-to-epoch/17257177#17257177 ?

**Comment by tikismoke** [comment]
I'm agree but for now the value of ''date'' looks like:

> datetime.datetime(2016, 9, 10, 11, 25, 7, 236000, tzinfo= isodate.tzinfo.Utc object at 0x7fc264cb0810)

Not:

> 2016, 9, 10, 11, 25, 7, 236000, something

Check the 1st exemple as for lat/lon as tought date will have a corect value.
For me this should be:
`Location(latitude=4xx.440586, longitude=xx.08945, altitude=xx5.2, satellites=10, heading=2xx.85, date=2016-09-10 11:25:7+01:00)`

Instead of:
`Location(latitude=4xx.440586, longitude=xx.08945, altitude=xx5.2, satellites=10, heading=2xx.85, date=datetime.datetime(2016, 9, 10, 11, 25, 7, 236000, tzinfo=<isodate.tzinfo.Utc object at 0x7fc264cb0810>))`

The problems seems to be in execution of isodate or datetime. It's not done, it's print as is in the entities.

**Comment by tikismoke** [comment]
Sorry miss understood your last question :(

Would you like some help to make your SDK return timestamp in entitys? I could have a look if you want.

And it will be easier in my plugins after ;)

**Comment by qk7b** [comment]
I got the point that a timestamp is what you need!

But the thing is, the API does not return a timestamp but a RF3339 date ! And I'd like to be as close as I can from the raw API.
As there is a TimeZone in the dates from the API (because data are in the TZ of the car), I think it has to be in the results.

But you can just do a conversion in your code to obtain a timestamp, can't you ?

**Comment by tikismoke** [comment]
Ok reject the p/r I'm going to have a look closer.

As I understand you want to be as close as possible as what the API return.

The time stamp part will be in the plugin of course.

We just need to find why date.datetime and isodate are not execute on your sdk

**Comment by tikismoke** [comment]
Pff i finally understand the difference :)
When printing it prints things un-understandable, but it's really a datime object usable with correct timezone.

In my apps i'll just have to:
timestamp = calendar.timegm(location.date.timetuple())
