### ISSUE TITLE
Tuple error with access token

### ISSUE THREAD

**Issue by tikismoke** [quentin7b/xee-sdk-python#2]
When i make a request get_user or get cars i got

```
Traceback (most recent call last):
  File "xee_exemple.py", line 23, in <module>
    car= xee.get_cars(token)
  File "/usr/local/lib/python2.7/dist-packages/xee-3.0.0-py2.7.egg/xee/sdk.py", line 162, in get_cars
    response = xee_utils.do_get_request(route, access_token)
  File "/usr/local/lib/python2.7/dist-packages/xee-3.0.0-py2.7.egg/xee/utils.py", line 35, in do_get_request
    request = requests.get(route, headers={'Authorization': 'Bearer ' + bearer})
TypeError: cannot concatenate 'str' and 'tuple' objects

```

if i print token i get:

> (Token(access_token=u'4f3efxxxxxxxxxa413868114c982a26d0dddaebfbfea110677a2caf6968c132', refresh_token=u'b7d0c2xxxxxxxxxx2bb1ad6282deefc10fae0ab2a89924914e757db386571', expires_in=172800, expires_at=1472999882), None)

Looks like the access token is not parse in  response = xee_utils.do_get_request(route, access_token)

i have to provide myself the current token like this to have an answer: response = xee_utils.do_get_request(route, '4f3efxxxxxxxxxa413868114c982a26d0dddaebfbfea110677a2caf6968c132')

**Comment by qk7b** [comment]
Yeah, 

In fact when you call `get_token_from_*()`, it returns a tuple with the `access_token` and the `refresh_token`.

So when you call `get_cars()`, you have to pass `token.access_token` ?

Or I misunderstood the error ?

**Comment by tikismoke** [comment]
Your right but it's you exemple on the readme page :) I'll propose a pull request for this on README.

if i pass token.access_token i get this error:

```
Traceback (most recent call last):
  File "xee_exemple.py", line 21, in <module>
    user = xee.get_user(token.access_token)
AttributeError: 'tuple' object has no attribute 'access_token'

```

**Comment by tikismoke** [comment]
Still the tuple object attribute to correct in last comment.
Still trying to find a solution for @domogik ;)

**Comment by qk7b** [comment]
Damn, I've read too fast.
Can you past the full code from _token fetching_ to `get_cars` call ?

**Comment by tikismoke** [comment]
```
#cat xee_exemple.py
from xee import Xee

xee = Xee(client_id="9QESM4Tqh5xxxx2uJhj1NP",
        client_secret="3brSxxxxxxxxxjaG",
        redirect_uri="http://localhost")

login_url = xee.get_authentication_url()

print("Go to %s allow the app and copy your oauth_verifier" %login_url)
authorization_code = raw_input('Please enter your authorization_code: ')

token = xee.get_token_from_code(authorization_code)
print token
tokenacess ="4551ecfa29f1xxxxxxxxxxxxb7985ef8929b"
user = xee.get_user(tokenacess)
print user
car = xee.get_cars(token.access_token)
print car
```

In this exemple i get the user info but not the cars one with error:

`AttributeError: 'tuple' object has no attribute 'access_token'`

I'm using python 2.7 maybe it comes from here too.

**Comment by tikismoke** [comment]
Token print looks like this:

> (Token(access_token=u'8598fad36379dffdxxxxxxxxxxxxcf44b73266c22c69bf3c', refresh_token=u'29ed2323xxxxxxxxxxxxxxxxx1719c2fd19a82214d3', expires_in=172800, expires_at=1473097041), None)

**Comment by tikismoke** [comment]
Found something.....
user = xee.get_user(token[0].access_token)

**Comment by qk7b** [comment]
Ho fine.

As (almost) every call to the SDK it returns a:

**response, error**

So may be try with this:

``` python
from xee import Xee

xee = Xee(client_id="9QESM4Tqh5xxxx2uJhj1NP",
        client_secret="3brSxxxxxxxxxjaG",
        redirect_uri="http://localhost")

login_url = xee.get_authentication_url()

print("Go to %s allow the app and copy your oauth_verifier" %login_url)
authorization_code = raw_input('Please enter your authorization_code: ')

token, error = xee.get_token_from_code(authorization_code)
print token
tokenacess ="4551ecfa29f1xxxxxxxxxxxxb7985ef8929b"
user, error = xee.get_user(tokenacess)
print user
car, error = xee.get_cars(token.access_token)
print car
```

**Comment by tikismoke** [comment]
Nice ;) this works.

Going to update the README a second time ;)

**Comment by qk7b** [comment]
Do you want to do this or ?
